export const products = [
    // Chairs
        {
            name:'Regazo Chaise',
            price:'14500.00',
            id:'regazo-chair',
            category:'Chaises',
            description:'',
            images:[
               {image:'https://i.postimg.cc/qRs1Xw58/product-1.jpg'},
               {image:'https://i.postimg.cc/yx7vfRM2/product-1-1.jpg'}
            ],
        },
        {
            name:'Pachonita Chaise',
            price:'14500.00',
            id:'pachonita-chair',
            category:'Chaises',
            description:'',
            images:[
                {image:'https://i.postimg.cc/s2s0Nr5c/product-2.jpg'},
                {image:'https://i.postimg.cc/LsD0dbTM/product-2-1.jpg'},
            ],
        },
        {
            name:'Reclinable Chaise',
            price:'14500.00',
            id:'reclinable-chair',
            category:'Chaises',
            description:'',
            images:[
                {image:'https://i.postimg.cc/yd4fZtv1/product-3.jpg'},
                {image:'https://i.postimg.cc/v8vP4P9y/product-3-1.jpg'},
            ],
        },
        {
            name:'Poltrona Chaise',
            price:'14500.00',
            id:'poltrona-chair',
            category:'Chaises',
            description:'',
            images:[
                {image:'https://i.postimg.cc/XqG85V5z/product-4.jpg'},
                {image:'https://i.postimg.cc/br7RHKHN/product-4-1.jpg'},
            ],
        },
        {
            name:'Calida Chaise',
            price:'14500.00',
            id:'calida-chair',
            category:'Chaises',
            description:'',
            images:[
                {image:'https://i.postimg.cc/XNrSLdcT/product-5.jpg'},
                {image:'https://i.postimg.cc/8kx80cZs/product-5-1.jpg'},
            ],
        },
        {
            name:'Descanso Chaise',
            price:'14500.00',
            id:'descanso-chair',
            category:'Chaises',
            description:'',
            images:[
                {image:'https://i.postimg.cc/65RsJKPc/product-6.jpg'},
                {image:'https://i.postimg.cc/BnGrJy90/product-6-1.jpg'},
            ],
        },
    // Tables
        {
            name:'Cozy Table',
            price:'17500.00',
            id:'cozy-table',
            category:'Tables',
            description:'',
            dimensions:"120cm/60cm",
            images:[
               {image:'https://i.postimg.cc/SNswk0P3/product-1.jpg',},
               {image:'https://i.postimg.cc/k580zxH5/product-1-1.jpg'}
            ],
        },
        {
            name:'Dream Table',
            price:'17500.00',
            id:'dream-table',
            category:'Tables',
            description:'',
            dimensions:"120cm/60cm",
            images:[
                {image:'https://i.postimg.cc/G3zZW3Xv/product-2.jpg'},
                {image:'https://i.postimg.cc/gjMQ84xg/product-2-1.jpg'},
            ],
        },
        // Meubles
        {
            name:'Meuble 1',
            price:'39500.00',
            id:'meuble-1',
            category:'Meubles',
            description:'',
            images:[
               {image:'https://i.postimg.cc/vTSfW6br/product-1.jpg',},
               {image:'https://i.postimg.cc/zX6TvWd5/product-1-1.jpg'}
            ],
        },
        {
            name:'Meuble 2',
            price:'36500.00',
            id:'meuble-2',
            category:'Meubles',
            description:'',
            images:[
               {image:'https://i.postimg.cc/XqXy77dp/product-2.jpg',},
               {image:'https://i.postimg.cc/65ydBzfY/product-2-1.jpg'}
            ],
        },
        {
            name:'Coiffeuse 1',
            price:'36500.00',
            id:'coiffeuse-1',
            category:'Meubles',
            description:'',
            images:[
               {image:'https://i.postimg.cc/ydJQmX4j/product-3.jpg'},
               {image:'https://i.postimg.cc/vBpP3gGs/product-3-1.jpg'}
            ],
        },
        {
            name:'Coiffeuse 2',
            price:'36500.00',
            id:'coiffeuse-2',
            category:'Meubles',
            description:'',
            images:[
               {image:'https://i.postimg.cc/hGxh3xwq/2822-2812.jpg'},
               {image:'https://i.postimg.cc/Kz24XjS3/20230726-102847.jpg'}
            ],
        },
        {
            name:'Coiffeuse 3',
            price:'36500.00',
            id:'coiffeuse-3',
            category:'Meubles',
            description:'',
            images:[
               {image:'https://i.postimg.cc/d1wQHfr8/IMG-6587.jpg'},
               {image:'https://i.postimg.cc/7Y6hrjc9/20230726-133651.jpg'}
            ],
        },
        {
            name:'Coiffeuse 4',
            price:'36500.00',
            id:'coiffeuse-4',
            category:'Meubles',
            description:'',
            images:[
                {image:'https://i.postimg.cc/wMWBsktD/20230726-135411.jpg'},
                {image:'https://i.postimg.cc/RFLhvm4s/20230726-135005.jpg'}
            ],
        },
        {
            name:'Coiffeuse 5',
            price:'36500.00',
            id:'coiffeuse-5',
            category:'Meubles',
            description:'',
            images:[
               {image:'https://i.postimg.cc/wMxvvrB6/20230726-140318.jpg'},
               {image:'https://i.postimg.cc/h4MvwKCh/20230726-140840.jpg'}
            ],
        },
        {
            name:'Meuble 3',
            price:'36500.00',
            id:'meuble-3',
            category:'Meubles',
            description:'',
            images:[
               {image:'https://i.postimg.cc/yxN1BSfx/IMG-6663.jpg'},
               {image:'https://i.postimg.cc/8cn1CP3H/IMG-6670.jpg'}
            ],
        },
        {
            name:'Meuble 4',
            price:'36500.00',
            id:'meuble-4',
            category:'Meubles',
            description:'',
            images:[
               {image:'https://i.postimg.cc/28K6k2ND/20230726-142251.jpg'},
               {image:'https://i.postimg.cc/cJqLYCJk/20230726-142406.jpg'}
            ],
        },
        {
            name:'Meuble 5',
            price:'36500.00',
            id:'meuble-5',
            category:'Meubles',
            description:'',
            images:[
               {image:'https://i.postimg.cc/FKjsxvdr/20230726-142820.jpg'},
               {image:'https://i.postimg.cc/Y9RrJxzT/IMG-6656.jpg'}
            ],
        },
        // Banquettes
        {
            name:'CozySeat',
            price:'17500.00',
            id:'cozyseat',
            category:'Banquettes',
            description:'',
            images:[
               {image:'https://i.postimg.cc/W1ds4qdG/product-1.jpg',},
               {image:'https://i.postimg.cc/1z6PGxc4/product-1-1.jpg'}
            ],
        },
        {
            name:'Relaxlounge',
            price:'17500.00',
            id:'relaxlounge',
            category:'Banquettes',
            description:'',
            images:[
               {image:'https://i.postimg.cc/y82s36Rw/product-2.jpg',},
               {image:'https://i.postimg.cc/26DYTH2G/product-2-1.jpg'}
            ],
        },
        {
            name:'SnugSofa',
            price:'17500.00',
            id:'snugsofa',
            category:'Banquettes',
            description:'',
            images:[
               {image:'https://i.postimg.cc/W1JBVvfS/product-3.jpg',},
               {image:'https://i.postimg.cc/15dkbtMf/product-3-1.jpg'}
            ],
        },
        {
            name:'Banquette A Caroux',
            price:'17500.00',
            id:'banquette-caroux',
            category:'Banquettes',
            description:'',
            images:[
               {image:'https://i.postimg.cc/0QbZtYRC/20230726-114004.jpg',},
               {image:'https://i.postimg.cc/HxRzFrT1/20230726-114043.jpg'}
            ],
        },
        {
            name:'Banquette Smoking',
            price:'17500.00',
            id:'banquette-smoking',
            category:'Banquettes',
            description:'',
            images:[
               {image:'https://i.postimg.cc/gkRtFHwS/20230726-112757.jpg',},
               {image:'https://i.postimg.cc/3xTSK0mK/20230726-112839.jpg'}
            ],
        },
        {
            name:'Banquette Couck',
            price:'17500.00',
            id:'banquette-couck',
            category:'Banquettes',
            description:'',
            images:[
                {image:'https://i.postimg.cc/3wLnCL6R/20230726-105218.jpg'},
                {image:'https://i.postimg.cc/nLV3m83g/20230726-105052.jpg',}
            ],
        },
        {
            name:'Banquette PatchWork ',
            price:'17500.00',
            id:'banquette-patchwork',
            category:'Banquettes',
            description:'',
            images:[
               {image:'https://i.postimg.cc/sDFKcGnp/20230726-114928.jpg',},
               {image:'https://i.postimg.cc/v8x3ftvY/20230726-115031.jpg'}
            ],
        },
]